[package]
name = "fabric-urc"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0", features = ["sol-types", "contract"] }
serde = { version = "1.0", features = ["derive"] }
blst = { workspace = true }
eyre = { workspace = true }
commit-boost = { workspace = true }