[package]
name = "fabric-binaries"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gateway"
path = "gateway.rs"

[[bin]]
name = "relay"
path = "relay.rs"

[[bin]]
name = "proposer"
path = "proposer.rs"

[[bin]]
name = "spammer"
path = "spammer.rs"

[[bin]]
name = "simulation-setup"
path = "simulation-setup.rs"

[[bin]]
name = "local-signer-module"
path = "local_signer_module.rs"

[[bin]]
name = "beacon-mock"
path = "beacon_mock.rs"

[dependencies]
commitments = { package = "fabric-commitments", path = "../crates/commitments" }
constraints = { package = "fabric-constraints", path = "../crates/constraints" }
common = { package = "fabric-common", path = "../crates/common" }
lookahead = { package = "fabric-lookahead", path = "../crates/lookahead" }
inclusion = { package = "fabric-inclusion", path = "../crates/inclusion" }
urc = { package = "fabric-urc", path = "../crates/urc" }

commit-boost = { workspace = true }
cb-common = { workspace = true }
cb-signer = { workspace = true }

alloy = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tracing-subscriber = { workspace = true }
indexmap = "2.2.6"
url = "2.5"
toml_edit = "0.23.9"
dotenv = "0.15.0"