[package]
name = "fabric-signing"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { workspace = true }
commit-boost = { workspace = true }
eyre = { workspace = true }
tracing = { workspace = true }